{
 "title": "system monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "jdbc connections and scrape duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "jdbc_connections",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "jdbc_connections_max" }
   ]
  },
  {
   "title": "scrape duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  { "title": "alerts and dashboard lists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "title": "alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 } },
  { "title": "Dashboard list", "type": "dashlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 } },
  { "title": "system cpu usage and count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "system cpu count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_count" }
   ]
  },
  {
   "title": "system cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "zuul exceptions and http requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "zuul exceptions",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "ZUUL::EXCEPTION:error:SendErrorFilter:500_total"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  }
 ]
}